/* Generated By:JavaCC: Do not edit this line. DingbatParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface DingbatParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LOCATION = 5;
  /** RegularExpression Id. */
  int ANCHOR = 6;
  /** RegularExpression Id. */
  int ROTATION = 7;
  /** RegularExpression Id. */
  int SIZE = 8;
  /** RegularExpression Id. */
  int SPACING = 9;
  /** RegularExpression Id. */
  int STYLING = 10;
  /** RegularExpression Id. */
  int SOLIDITY = 11;
  /** RegularExpression Id. */
  int CONTAINS = 12;
  /** RegularExpression Id. */
  int SHAPE = 13;
  /** RegularExpression Id. */
  int SYMBOL = 14;
  /** RegularExpression Id. */
  int SHAPES = 15;
  /** RegularExpression Id. */
  int ALPHA = 16;
  /** RegularExpression Id. */
  int DIGIT = 17;
  /** RegularExpression Id. */
  int DIRECTION = 18;
  /** RegularExpression Id. */
  int POS = 19;
  /** RegularExpression Id. */
  int ID = 20;
  /** RegularExpression Id. */
  int MEASURE = 21;
  /** RegularExpression Id. */
  int STYLE = 22;
  /** RegularExpression Id. */
  int FORMAT = 23;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"loc\"",
    "\"anchor\"",
    "\"rot\"",
    "\"size\"",
    "\"sp\"",
    "\"style\"",
    "\"sol\"",
    "\"con\"",
    "\"shape\"",
    "<SYMBOL>",
    "<SHAPES>",
    "<ALPHA>",
    "<DIGIT>",
    "<DIRECTION>",
    "<POS>",
    "<ID>",
    "<MEASURE>",
    "<STYLE>",
    "<FORMAT>",
    "\"[\"",
    "\":\"",
    "\"]\"",
    "\";\"",
    "\"(\"",
    "\")\"",
  };

}
